trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'Azure subscription'
  resourceGroup: 'testRG'
  aksCluster: 'testCluster'
  chartPath: '$(System.DefaultWorkingDirectory)/helm-chart/helloworld'

stages:
# STAGE 1: DEV (Runs automatically)
- stage: DeployDev
  displayName: 'Deploy to DEV'
  jobs:
  - template: build-template.yml
    parameters:
      environmentName: 'dev'
      k8sNamespace: 'dev-ns'
      releaseName: 'hello-world-app-dev'

# STAGE 2: QA (Waits for QA approval in Azure DevOps Environments UI)
- stage: DeployQA
  displayName: 'Deploy to QA'
  dependsOn: DeployDev
  jobs:
  - template: build-template.yml
    parameters:
      environmentName: 'qa'
      k8sNamespace: 'qa-ns'
      releaseName: 'hello-world-app-qa'

# STAGE 3: PROD (Waits for PROD approval in Azure DevOps Environments UI)
- stage: DeployProd
  displayName: 'Deploy to PROD'
  dependsOn: DeployQA
  jobs:
  - template: build-template.yml
    parameters:
      environmentName: 'prod'
      k8sNamespace: 'prod-ns'
      releaseName: 'hello-world-app-prod'
